@Prodentia.API_HostAddress = http://localhost:5022/api/appointments

###
GET {{Prodentia.API_HostAddress}}?pageNumber=1&pageSize=5&name=dentist
Accept: application/json

###

GET {{Prodentia.API_HostAddress}}/019fb7fd-9e42-71cb-bfe0-96b7c7295e9f
Accept: application/json

###

POST {{Prodentia.API_HostAddress}}
Content-Type: application/json
{
  "dentistId": "019fb7fc-a614-7247-a250-1cec67b51b37",
  "patientId": "019fcc7f-d1d7-7f4c-92c6-6e870f310e8a",
  "dentalOfficeId":"019fcc80-74d6-7ba5-a994-19b4f782b216",
  "startDate":"2026-11-01T09:30:00",
  "endDate":"2026-11-01T09:40:00"
}

###

PUT {{Prodentia.API_HostAddress}}/019fb7fd-9e42-71cb-bfe0-96b7c7295e9e
Content-Type: application/json
{
    "name": "dentist name 002 - u",
    "email": "dentistuser002@example.comu"
}
###

DELETE {{Prodentia.API_HostAddress}}/019fb888-bfe4-76e8-af04-c5c6e34915ed

###
