@Prodentia.API_HostAddress = http://localhost:5022/api/appointments

###
GET {{Prodentia.API_HostAddress}}?startDate=2026-11-01&endDate=2026-11-30&dentalOfficeId=019FD0FB-8C11-7D85-8235-D5C9EFDF01A4&dentistId=019FD0FA-2875-71B4-A47E-2414E2C014AD
Accept: application/json

###

GET {{Prodentia.API_HostAddress}}/019FCC96-A2C5-76A7-849F-E4F150EDC60B
Accept: application/json

###

POST {{Prodentia.API_HostAddress}}
Content-Type: application/json
{
  "dentistId": "019FD0FA-12F4-79D9-9C50-680715CC7469",
  "patientId": "019FD0FB-1C22-7E1E-8C11-CA1E2D215245",
  "dentalOfficeId":"019FD0FB-8C11-7D85-8235-D5C9EFDF01A4",
  "startDate":"2026-11-02T10:50:00",
  "endDate":"2026-11-02T11:00:00"
}

###

PUT {{Prodentia.API_HostAddress}}/019fb7fd-9e42-71cb-bfe0-96b7c7295e9e
Content-Type: application/json
{
    "name": "dentist name 002 - u",
    "email": "dentistuser002@example.comu"
}
###

DELETE {{Prodentia.API_HostAddress}}/019fb888-bfe4-76e8-af04-c5c6e34915ed

###
