@Prodentia.API_HostAddress = http://localhost:5022/api/appointments

###
GET {{Prodentia.API_HostAddress}}?startDate=2026-11-01&endDate=2026-11-30&dentalOfficeId=019FD0FB-8C11-7D85-8235-D5C9EFDF01A4&dentistId=019FD0FA-12F4-79D9-9C50-680715CC7469
Accept: application/json

###

GET {{Prodentia.API_HostAddress}}/019FCC96-A2C5-76A7-849F-E4F150EDC60B
Accept: application/json

###

POST {{Prodentia.API_HostAddress}}
Content-Type: application/json
{
  "dentistId": "019FD0FA-12F4-79D9-9C50-680715CC7469",
  "patientId": "019fd0fa-f86d-7375-8c85-ad1a60fad2c3",
  "dentalOfficeId":"019FD0FB-8C11-7D85-8235-D5C9EFDF01A4",
  "startDate":"2026-11-03T10:50:00",
  "endDate":"2026-11-03T11:00:00"
}

###

POST {{Prodentia.API_HostAddress}}/019FCC96-A2C5-76A7-849F-E4F150EDC60B/complete

###

POST {{Prodentia.API_HostAddress}}/019FD0FC-73D5-7B5E-80A3-E3BEA422DC92/cancel

###
