@Prodentia.API_HostAddress = http://localhost:5022/api/patients

###
GET {{Prodentia.API_HostAddress}}?pageNumber=1&pageSize=5&name=user
Accept: application/json

###

GET {{Prodentia.API_HostAddress}}/019f8417-ab99-7634-b106-f10bc96630fe
Accept: application/json

###

POST {{Prodentia.API_HostAddress}}
Content-Type: application/json
{
  "name": "patient004",
  "email": "patient004@example.com"
}

###

PUT {{Prodentia.API_HostAddress}}/019f7e7b-7d96-7a05-aba4-11ae61c9cc9d
Content-Type: application/json
{
    "name": "user name 002 delete - u",
    "email": "deleteuser002@example.comu"
}
###

DELETE {{Prodentia.API_HostAddress}}/019f7e7b-7d96-7a05-aba4-11ae61c9cc9d

###
