@Prodentia.API_HostAddress = http://localhost:5022/api/dentaloffices

###
GET {{Prodentia.API_HostAddress}}
Accept: application/json

###

GET {{Prodentia.API_HostAddress}}/019f4255-21a9-7315-9cee-fc75e06b1801
Accept: application/json

###

POST {{Prodentia.API_HostAddress}}
Content-Type: application/json
{
  "name": "Dental Office A004"
}

###

PUT {{Prodentia.API_HostAddress}}/019f4255-21a9-7315-9cee-fc75e06b1801
Content-Type: application/json
{
  "name": "Dental Office A004 - Updated"
}
###