name: prodentia

version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: prodentia-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ProdentiaDev@2024!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - prodentia-network
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "ProdentiaDev@2024!", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

networks:
  prodentia-network:
    driver: bridge